# The URL the site will be built for
base_url = "https://ryansullivan.dev"

title = "Ryan Sullivan Dev"
description = "Ryan Sullivan's developer portfolio"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language; used in feeds.
default_language = "en"

[extra]
# User settings
username = "Ryan Sullivan"
user_description = "Building engaging user experiences with modern frontend technology"
user_title = "Frontend Developer"
email = "mrsulliv@gmail.com"
github_username =  "rysllvn"

# Google-analytics
google_analytics.id = ""
